apiVersion: v1
kind: Service
metadata:
    name: "sarra-cc72"
    labels:
        app: "sarra-cc72"
spec:
    type: LoadBalancer
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "sarra-cc72"